variable "internet-gateway-id" {}
variable "customer" {}
variable "environment" {}
variable "public-subnet" {}
variable "vpc" {}
variable "amazon-linux-2" {}
variable "rds-username" {}
variable "rds-endpoint" {}
variable "rds-password" {}
variable "rds-db-name" {}