apiVersion: apps/v1
kind: Deployment
metadata:
 name: keycloak
 labels:
  name: keycloak
  app: keycloak-app
spec:
  replicas: 1
  selector:
   matchLabels:
    name: keycloak-app-pod
    app: keycloak-app
  template:
   metadata:
     name: keycloak-app-pod
     labels:
      name: keycloak-app-pod  
      app: keycloak-app
   spec:
     containers:
       - name: keycloak-app
         image: quay.io/keycloak/keycloak:18.0.0
        #  command: ["/bin/sh"]
         args: [ "start" ]
         env:
         - name: KEYCLOAK_ADMIN
           value: qs-admin
         - name: KEYCLOAK_ADMIN_PASSWORD
           value: dem0azUba
         - name: KEYCLOAK_HOSTNAME
           value: "keycloak"
         - name: KC_HOSTNAME_STRICT
           value: "false"
         - name: KC_HOSTNAME
           value: eks-keycloak-dev.stella-apps.com
         - name: KC_PROXY
           value: "edge"
         - name: KC_HTTPS_PORT
           value: "8443"
        #  - name: KC_CACHE_STACK
        #    value: kubernetes
        #  - name: PROXY_ADDRESS_FORWARDING
        #    value: "true"
         ports:
           - containerPort: 8080
         ports:
           - containerPort: 8443
         imagePullPolicy: Always
         
    #  imagePullSecrets:
    #  - name: ecr-stella
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-svc
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  type: NodePort
  selector:
    app: keycloak-app
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keycloak-https
  annotations:
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-west-2:055638961298:certificate/0d5e5df9-3360-4081-9882-262de32c6f54
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS":443}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    # alb.ingress.kubernetes.io/healthcheck-protocol: HTTPS
    # alb.ingress.kubernetes.io/healthcheck-port: '8443'
    alb.ingress.kubernetes.io/tags: Environment=dev,Team=test
spec:
  ingressClassName: alb
  rules:
    - host: eks-keycloak-dev.stella-apps.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: keycloak-svc
                port:
                  number: 80
# apiVersion: v1
# kind: Service
# metadata:
#   name: keycloak-https
#   # namespace: 5-example
#   annotations:
#     service.beta.kubernetes.io/aws-load-balancer-type: external
#     service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
#     service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
#     # service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
# spec:
#   ports:
#   - port: 443
#     targetPort: 8443
#     protocol: TCP
#   type: LoadBalancer
#   selector:
#     app: keycloak-app