
apiVersion: v1
kind: Secret
metadata:
  name: soum-demo-secret
type: Opaque
stringData:
  AWS_BUCKET_NAME: cat-devops-test
  AWS_ACCESS_KEY: 'AKIAQZ5CXFSJB3MJR2AS'
  AWS_SECRET_ACCESS_KEY: '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'
---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: soum-demo
  name: soum-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: soum-demo
  template:
    metadata:
      labels:
        app: soum-demo
    spec:
      containers:
      - image: docker.io/coreopt1/atiframzan:soum-demo
        name: soum-demo
        imagePullPolicy: Always
        envFrom:
          - secretRef:
              name: soum-demo-secret
      imagePullSecrets:
      - name: myregistrykey
        
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: soum-demo
  name: soum-demo-svc
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: soum-demo
  type: LoadBalancer

